"""
model_reasoner.py — Stage C AI Clinical Brief Reasoner.

Manages BioMistral VRAM eviction and invocation, producing a scannable, structured
JSON clinical brief (flags_to_discuss, tests_to_order, patterns_identified, urgent_actions,
and mandatory safety disclaimer).
"""
import json
import os
import re
from typing import Any, Dict, List, Optional
try:
    from loguru import logger
except ImportError:
    import logging
    logger = logging.getLogger("model_reasoner")

try:
    from backend.gpu_manager import evict_chandra, evict_ollama
except ImportError:
    try:
        from gpu_manager import evict_chandra, evict_ollama
    except ImportError:
        def evict_chandra(): pass
        def evict_ollama(*args, **kwargs): pass

MANDATORY_DISCLAIMER = (
    "DISCLAIMER: This report is generated by an automated clinical decision-support pipeline. "
    "It is intended solely to assist licensed medical professionals and does NOT constitute a final "
    "medical diagnosis, prognosis, or treatment plan. All findings and suggestions must be verified "
    "against clinical presentation, imaging, and official lab reports by a qualified physician."
)

STAGE_C_SYSTEM_PROMPT = """You are an expert clinical assistant.
Your goal is to parse the provided medical document (raw OCR text) and clinical decision support context to produce a high-impact, scannable brief for a physician.

CRITICAL INSTRUCTIONS:
1. Return VALID JSON ONLY. Do NOT write prose paragraphs, preambles, or markdown formatting.
2. The JSON object MUST contain exactly these 5 keys:
   - "patient_info": object containing {{"name": string, "age": string, "gender": string, "reg_date": string}} (extract from text if present, else "Unspecified")
   - "document_type": string (e.g. "Serology Report", "Prescription", "Liver Function Panel", "Consultation Note", "Radiology / Ultrasound")
   - "flagged_findings": list of objects containing {{"item": string, "status": string, "detail": string, "is_critical": boolean}}
     (e.g., {{"item": "HCV Screening", "status": "REACTIVE 🚨", "detail": "Advise confirmation by ELISA", "is_critical": true}})
   - "actionable_recommendations": list of strings (immediate follow-up investigations or clinical actions)
   - "physician_quick_bullets": list of 2-3 concise strings (key talking points for a 5-second doctor consultation)

3. Base your extraction strictly on the raw OCR text provided below. Do NOT invent diagnoses or hallucinate non-existent lab values.

RAW OCR TEXT FROM DOCUMENT:
{raw_ocr_text}

SUPPLEMENTAL CLINICAL FINDINGS (IF AVAILABLE):
{findings_json}

DIFFERENTIAL DIAGNOSES (IF AVAILABLE):
{differentials_json}
"""


def _clean_json_output(raw_text: str) -> Optional[Dict[str, Any]]:
    """Clean markdown backticks or extra whitespace and parse JSON."""
    if not raw_text:
        return None
    cleaned = raw_text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        data = json.loads(cleaned)
        if isinstance(data, dict):
            return data
    except Exception:
        pass

    # Regex extraction fallback for JSON block
    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if match:
        try:
            data = json.loads(match.group(0))
            if isinstance(data, dict):
                return data
        except Exception:
            pass
    return None


def _build_rule_fallback(
    findings: Dict[str, Any],
    differentials: List[Dict[str, Any]],
    raw_ocr_text: str = "",
) -> Dict[str, Any]:
    """Generate structured 5-section clinical brief directly from text & rules when AI is unavailable/disabled."""
    # Regex extract patient metadata
    name_match = re.search(r"Patient\s*Name\s*:\s*([^\n\r,]+)", raw_ocr_text, re.IGNORECASE)
    age_match = re.search(r"Age\s*/?\s*Gender\s*:\s*([^\n\r,]+)", raw_ocr_text, re.IGNORECASE)
    date_match = re.search(r"Reported\s*On\s*:\s*([^\n\r,]+)", raw_ocr_text, re.IGNORECASE)

    patient_name = name_match.group(1).strip() if name_match else "Unspecified"
    age_gender = age_match.group(1).strip() if age_match else "Unspecified"
    reg_date = date_match.group(1).strip() if date_match else "Unspecified"

    age = "Unspecified"
    gender = "Unspecified"
    if "/" in age_gender:
        parts = age_gender.split("/", 1)
        age = parts[0].strip()
        gender = parts[1].strip()

    # Determine document type
    ocr_upper = raw_ocr_text.upper()
    if "SEROLOGY" in ocr_upper or "HCV" in ocr_upper or "HBSAG" in ocr_upper:
        doc_type = "Serology Report"
    elif "PRESCRIPTION" in ocr_upper or "RX" in ocr_upper:
        doc_type = "Prescription"
    elif "LIVER" in ocr_upper or "ALT" in ocr_upper or "AST" in ocr_upper:
        doc_type = "Liver Function Panel"
    elif "ULTRASOUND" in ocr_upper or "SONOGRAPHY" in ocr_upper:
        doc_type = "Radiology Report"
    else:
        doc_type = "Medical Report"

    flagged_findings: List[Dict[str, Any]] = []

    # Check for Serology reactive findings in OCR
    if "HCV" in ocr_upper and "REACTIVE" in ocr_upper:
        flagged_findings.append({
            "item": "HCV Screening",
            "status": "REACTIVE 🚨",
            "detail": "Advise confirmation by ELISA / HCV RNA PCR",
            "is_critical": True
        })
    if "HBSAG" in ocr_upper:
        is_react = "REACTIVE" in ocr_upper and "HBSAG" in ocr_upper
        flagged_findings.append({
            "item": "HBsAg Screening",
            "status": "Reactive 🚨" if is_react else "Non-Reactive",
            "detail": "Hepatitis B Surface Antigen",
            "is_critical": is_react
        })

    # Add numeric lab fold abnormalities
    extracted = findings.get("extracted_values", {})
    folds = findings.get("fold_over_uln", {})
    for k, v in extracted.items():
        fold = folds.get(k)
        if fold and fold > 1.0:
            flagged_findings.append({
                "item": k,
                "status": f"ELEVATED ({fold}x ULN)",
                "detail": f"Value: {v}",
                "is_critical": fold >= 3.0
            })

    actionable_recommendations: List[str] = []
    if any(f["item"] == "HCV Screening" and "REACTIVE" in f["status"] for f in flagged_findings):
        actionable_recommendations.append("Order HCV RNA Quantitative PCR for viral load confirmation")
        actionable_recommendations.append("Schedule Hepatology / Gastroenterology consultation")

    for diff in differentials[:2]:
        for t in diff.get("recommended_tests", []):
            if t not in actionable_recommendations:
                actionable_recommendations.append(t)

    if not actionable_recommendations:
        actionable_recommendations.append("Clinical correlation and routine follow-up recommended")

    physician_quick_bullets: List[str] = []
    if flagged_findings:
        crit_names = [f["item"] for f in flagged_findings if f["is_critical"]]
        if crit_names:
            physician_quick_bullets.append(f"Critical abnormal findings detected: {', '.join(crit_names)}")
        else:
            physician_quick_bullets.append("Key findings reviewed; routine follow-up advised")
    else:
        physician_quick_bullets.append("All extracted parameters are within expected limits")

    if doc_type == "Serology Report":
        physician_quick_bullets.append("Advise patient on Serology screening results and confirmatory protocol")

    # Maintain backward compatibility keys
    flags_to_discuss = [f"{f['item']}: {f['status']} ({f['detail']})" for f in flagged_findings]

    return {
        "patient_info": {
            "name": patient_name,
            "age": age,
            "gender": gender,
            "reg_date": reg_date,
        },
        "document_type": doc_type,
        "flagged_findings": flagged_findings,
        "actionable_recommendations": actionable_recommendations,
        "physician_quick_bullets": physician_quick_bullets,
        "flags_to_discuss": flags_to_discuss,
        "tests_to_order": actionable_recommendations,
        "patterns_identified": [f"{doc_type} evaluated"],
        "urgent_actions": [f["item"] for f in flagged_findings if f["is_critical"]],
        "disclaimer": MANDATORY_DISCLAIMER,
        "ai_reasoning_available": False,
    }


def model_reason(
    findings: Dict[str, Any],
    differentials: List[Dict[str, Any]],
    llm_client: Optional[Any] = None,
    raw_ocr_text: str = "",
) -> Dict[str, Any]:
    """
    Generate structured 5-section AI clinical brief using BioMistral with VRAM eviction and rule fallback.

    :param findings: Pattern findings from Stage A.
    :param differentials: Differential list from Stage B.
    :param llm_client: Optional LLM client (e.g. OllamaLLMClient).
    :param raw_ocr_text: Raw text output from OCR engine.
    :return: Dict containing 5-section JSON brief for physician efficiency.
    """
    stage_c_enabled = os.environ.get("DIAGNOSIS_STAGE_C_ENABLED", "1") != "0"

    if not stage_c_enabled or llm_client is None:
        logger.info("Stage C AI reasoner skipped or disabled; using structured rule fallback.")
        return _build_rule_fallback(findings, differentials, raw_ocr_text)

    # Trigger VRAM eviction before loading heavy LLM
    try:
        evict_chandra()
        evict_ollama()
        try:
            import torch
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        except ImportError:
            pass
        logger.info("[model_reasoner] Pre-LLM VRAM eviction executed successfully.")
    except Exception as e:
        logger.warning(f"[model_reasoner] VRAM eviction warning: {e}")

    try:
        prompt_input = STAGE_C_SYSTEM_PROMPT.format(
            raw_ocr_text=raw_ocr_text or "No raw text available",
            findings_json=json.dumps(findings, indent=2),
            differentials_json=json.dumps(differentials, indent=2),
        )

        # Call LLM client with temperature 0.2 and max_tokens 512
        raw_resp = llm_client.complete(
            prompt=prompt_input,
            input="",
            temperature=0.2,
            max_new_tokens=512,
        )

        parsed = _clean_json_output(raw_resp)
        if parsed and isinstance(parsed, dict) and "patient_info" in parsed:
            # Ensure mandatory keys and disclaimer
            parsed["disclaimer"] = MANDATORY_DISCLAIMER
            parsed["ai_reasoning_available"] = True
            if "flags_to_discuss" not in parsed:
                parsed["flags_to_discuss"] = [
                    f"{f.get('item')}: {f.get('status')}" for f in parsed.get("flagged_findings", [])
                ]
            if "tests_to_order" not in parsed:
                parsed["tests_to_order"] = parsed.get("actionable_recommendations", [])
            return parsed

        logger.warning("[model_reasoner] LLM output unparseable or missing keys, using fallback.")
        return _build_rule_fallback(findings, differentials, raw_ocr_text)

    except Exception as err:
        logger.error(f"[model_reasoner] LLM invocation failed: {err}, falling back.")
        return _build_rule_fallback(findings, differentials, raw_ocr_text)

