"""
report_generator.py — Stage D Report Generator & Text Summariser.

Assembles the full structured report payload and generates a scannable, bullet-point
plain-text summary for physicians, ensuring mandatory safety disclaimers are present.
"""
from datetime import datetime, timezone
from typing import Any, Dict, List

try:
    from backend.diagnosis.model_reasoner import MANDATORY_DISCLAIMER
    from backend.diagnosis.hepatology_kb import HEPATOLOGY_REFERENCE_RANGES
except ImportError:
    from diagnosis.model_reasoner import MANDATORY_DISCLAIMER
    from diagnosis.hepatology_kb import HEPATOLOGY_REFERENCE_RANGES


def generate_report(
    findings: Dict[str, Any],
    scores: Dict[str, Any],
    differentials: List[Dict[str, Any]],
    reasoning: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Assemble structured 4-stage hepatology diagnosis report.

    :param findings: Stage A pattern findings.
    :param scores: Clinical severity scores (MELD, Child-Pugh, FIB-4).
    :param differentials: Stage B differential diagnoses list.
    :param reasoning: Stage C AI clinical brief.
    :return: Full report dictionary matching contract.
    """
    extracted = findings.get("extracted_values", {})
    folds = findings.get("fold_over_uln", {})
    raw_flags = findings.get("raw_flags", {})

    abnormal_findings: List[Dict[str, Any]] = []
    for k, v in extracted.items():
        ref = HEPATOLOGY_REFERENCE_RANGES.get(k)
        if ref:
            is_abnormal = False
            if ref.get("high") and v > ref["high"]:
                is_abnormal = True
            elif ref.get("low") and v < ref["low"]:
                is_abnormal = True

            if is_abnormal:
                abnormal_findings.append(
                    {
                        "test": k,
                        "value": v,
                        "fold_over_uln": folds.get(k),
                        "unit": ref.get("unit", ""),
                        "flag": raw_flags.get(k, "HIGH" if (ref.get("high") and v > ref["high"]) else "LOW"),
                    }
                )

    clinical_brief = {
        "flags_to_discuss": reasoning.get("flags_to_discuss", []),
        "tests_to_order": reasoning.get("tests_to_order", []),
        "patterns_identified": reasoning.get("patterns_identified", []),
        "urgent_actions": reasoning.get("urgent_actions", []),
    }

    # Deduped union of urgent actions + top differential recommended tests
    recommendations: List[str] = list(clinical_brief["urgent_actions"])
    for diff in differentials[:3]:
        for t in diff.get("recommended_tests", []):
            if t not in recommendations:
                recommendations.append(t)

    now_iso = datetime.now(timezone.utc).isoformat()

    return {
        "report_version": "2.0.0",
        "generated_at": now_iso,
        "department": "Hepatology & Gastroenterology Decision Support",
        "disclaimer": MANDATORY_DISCLAIMER,
        "abnormal_findings": abnormal_findings,
        "pattern_analysis": {
            "primary_pattern": findings.get("primary_pattern", "Normal"),
            "r_factor": findings.get("r_factor"),
            "de_ritis": findings.get("de_ritis"),
            "synthetic_dysfunction": findings.get("synthetic_dysfunction", False),
            "urgent_flags": findings.get("urgent_flags", []),
        },
        "severity_scores": scores,
        "differential_diagnoses": differentials,
        "clinical_brief": clinical_brief,
        "recommendations": recommendations,
    }


def generate_text_summary(report: Dict[str, Any]) -> str:
    """
    Generate a scannable bullet-point text summary for quick physician review.

    :param report: Report dict generated by generate_report().
    :return: Formatted plain text string containing the mandatory disclaimer.
    """
    pattern_info = report.get("pattern_analysis", {})
    abnormals = report.get("abnormal_findings", [])
    diffs = report.get("differential_diagnoses", [])
    scores = report.get("severity_scores", {})
    brief = report.get("clinical_brief", {})

    top_diff = diffs[0] if diffs else {"condition": "None", "confidence_label": "N/A", "probability": 0.0}

    lines = [
        "=================================================================",
        "                 HEPATOLOGY DIAGNOSIS SUMMARY                    ",
        "=================================================================",
        f"• Evaluated Findings : {len(abnormals)} abnormal lab parameter(s) detected",
        f"• Primary Pattern    : {pattern_info.get('primary_pattern', 'Normal')} "
        f"(De Ritis: {pattern_info.get('de_ritis')}, R-Factor: {pattern_info.get('r_factor')})",
        f"• Top Differential   : {top_diff.get('condition')} "
        f"[{top_diff.get('confidence_label')}, {top_diff.get('probability', 0.0)*100:.0f}% probability]",
    ]

    # Scores
    score_strs = []
    meld_val = scores.get("meld", {}).get("value")
    if meld_val is not None:
        score_strs.append(f"MELD: {meld_val}")

    cp_grade = scores.get("child_pugh", {}).get("class_grade")
    if cp_grade is not None:
        score_strs.append(f"Child-Pugh: {cp_grade}")

    fib4_val = scores.get("fib4", {}).get("value")
    if fib4_val is not None:
        score_strs.append(f"FIB-4: {fib4_val}")

    if score_strs:
        lines.append(f"• Severity Scores    : {', '.join(score_strs)}")

    # Urgent actions
    urgent_actions = brief.get("urgent_actions", [])
    if urgent_actions:
        lines.append(f"• URGENT ACTIONS     : {'; '.join(urgent_actions)}")
    else:
        lines.append("• Urgent Actions     : None required at present")

    # Recommended tests
    tests = brief.get("tests_to_order", [])
    if tests:
        lines.append(f"• Key Rec. Tests     : {', '.join(tests[:4])}")

    lines.append("")
    lines.append(MANDATORY_DISCLAIMER)

    return "\n".join(lines)
